#!groovy

node('node') {
    currentBuild.result = "SUCCESS"
    env.CI = "true"
    try {
       stage('Checkout'){
          checkout scm
       }

       stage('BuildAndTest'){
          docker build -t richardzone/quokka-test-docker3-image .
          docker run --rm richardzone/quokka-test-docker3-image npm test
       }

       stage('PushAppImage'){
          docker push richardzone/quokka-test-docker3-image
       }

       stage('DeployToDev'){
          docker run --rm -d -p 3001:3000 richardzone/quokka-test-docker3-image
       }

       stage('DeployToTest'){
          docker run --rm -d -p 3002:3000 richardzone/quokka-test-docker3-image
       }

       stage('DeployToProd'){
          docker run --rm -d -p 3003:3000 richardzone/quokka-test-docker3-image
       }


    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }

}
